nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['*'] # Autorise toutes les origines
        allow_headers: ['*'] # Autorise tous les en-têtes
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS'] # Méthodes autorisées
        max_age: 3600
    paths:
        '^/': # Applique cette configuration à toutes les routes
            origin_regex: true
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            max_age: 3600